### ISSUE TITLE
Error relating to Tidal when trying to use with Spotify

### ISSUE THREAD

**Issue by radusuciu** [0xf4b1/traktor-streaming-proxy#12]
Hi, great project!

I'm having some trouble getting it running, potentially due to this error:

```
Exception in thread "main" java.lang.NullPointerException: prop.getProperty("tidal.clientId") must not be null
   at sources.Tidal.<init>(Tidal.kt:15)
   at MainKt.main(Main.kt:74)
   at MainKt.main(Main.kt)
```

Do I have to have a Tidal account even if I don't intend to use it as a source? Spotify auth seems to go work once `spotify.username` and `spotify.password` are added to `config.properties` but when I attempt to curl the server nginx returns a 502 Bad Gateway as if the reverse proxied endpoint isn't accepting requests at port 8000.

I'm running this with docker compose, after generating certs with the provided script. Here is my compose file:

```yaml
services:
  traktor:
    image: ghcr.io/0xf4b1/traktor-streaming-proxy:v0.3-amd64
    volumes:
      - ./server.crt:/app/cert/server.crt
      - ./server.key:/app/cert/server.key
      - ./config.properties:/app/config.properties
    ports:
      - "443:443"
    init: true
```

Note that the tag is necessary because `latest` points to the arm release.
