### ISSUE TITLE
Cannot authenticate

### ISSUE THREAD

**Issue by radusuciu** [0xf4b1/traktor-streaming-proxy#13]
I'm attempting to set this up in Windows using WSL on Traktor 3.10. I am able to stand up the project using the provided docker image, and get the expected JSON response when navigating to https://api.beatport.com/v4/catalog/genres/ in the browser (other endpoints that don't require some dynamic id also work), as suggested in the README. I've also added the generated cert to the Windows cert store, edited the hosts file and have verified that there are no SSL issues/warnings:

![image](https://github.com/0xf4b1/traktor-streaming-proxy/assets/1108600/c6aee2fc-e51c-4431-9e87-468247ff5051)

However, when I attempt to authenticate in Traktor (this is after flushing DNS and even a restart), I get this error:

![image](https://github.com/0xf4b1/traktor-streaming-proxy/assets/1108600/c37dd651-a147-42a4-80ab-8a7179949077)

and here are the associated logs as output by docker compose:

```
traktor-streaming-proxy-traktor-1  | 392767 [eventLoopGroupProxy-4-13] INFO ktor.application  - 302 Found: GET - /v4/auth/o/authorize/ in 0ms -> traktor://bp_oauth?code=foo
traktor-streaming-proxy-traktor-1  | 397384 [eventLoopGroupProxy-4-14] INFO ktor.application  - 200 OK: GET - /v4/auth/logout/ in 0ms
```

Using fiddler, I see these requests:

```
GET https://api.beatport.com/v4/auth/o/authorize/?client_id=bNGKE97x70L0C5hyv5gsnpQHo9EYR5aA2RQPlbsL&response_type=code&redirect_uri=traktor://bp_oauth
302 Redirect to traktor://bp_oauth?code=foo

GET https://api.beatport.com/v4/auth/logout/
200 OK ()
```

matching the logs. I cleared all cookies from my browser (Firefox) just in case, with the same result.

Here is my `docker-compose.yml`:

```yaml
services:
  traktor:
    image: ghcr.io/0xf4b1/traktor-streaming-proxy:v0.3-amd64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./server.crt:/app/cert/server.crt
      - ./server.key:/app/cert/server.key
      - ./config.properties:/app/config.properties
      - ./license:/app/license
    ports:
      - "443:443"
    init: true
```

and `config.properties`:

```
#
#Fri Sep 29 03:37:37 GMT 2023
beatport.accountId=1337338
spotify.password=<redacted>
spotify.username=<redacted>
tidal.countryCode=foo
tidal.userId=1337
tidal.clientId=foo
tidal.accessToken=foo
tidal.refreshToken=foo
```

Other things I've tried:
- logging in with my actual Beatport subscription, the editing my hosts file, and then attempting to connect. In that case I can see Beatport in the Traktor interface, but I could not get a listing of any of the categories despite the endpoint being accessible as shown above.
- rebuilding the image locally with all Tidal related features scrubbed, which I figured I'd try after having some issues (see #12) with Tidal, despite the fact that your solution there worked (this is why it's not listed in the screenshot above, but results were the same with the pre-built image)

Thanks again for putting this out there, and again awesome project! I've never developed anything with Kotlin but it seems like a great choice for this based on the terseness of the code. Please let me know if I can provide any other details. My hunch is that either I'm doing something wrong (likely!) or maybe the fairly recent Traktor 3.10 update has changed the auth flow in some way.
